packages:
  - "frontend"
  - "backend"

onlyBuiltDependencies:
  - "@firebase/util"
  - "@sentry-internal/node-cpu-profiler"
  - "bcrypt"
  - "msgpackr-extract"
  - "protobufjs"
  - "unrs-resolver"
  - "@sentry/cli"
  - "esbuild"
  - "sharp"
  - "@pnpm/exe"