export enum AnalysisType {
  CHARACTERS = "characters",
  THEMES = "themes",
  STRUCTURE = "structure",
  SCREENPLAY = "screenplay",
  QUICK = "quick",
  DETAILED = "detailed",
  FULL = "full",
}

export enum TaskType {
  ANALYSIS = "analysis",
  CREATIVE = "creative",
  INTEGRATED = "integrated",
  COMPLETION = "completion",
  RHYTHM_MAPPING = "rhythm-mapping",
  CHARACTER_NETWORK = "character-network",
  DIALOGUE_FORENSICS = "dialogue-forensics",
  THEMATIC_MINING = "thematic-mining",
  STYLE_FINGERPRINT = "style-fingerprint",
  CONFLICT_DYNAMICS = "conflict-dynamics",
  ADAPTIVE_REWRITING = "adaptive-rewriting",
  SCENE_GENERATOR = "scene-generator",
  CHARACTER_VOICE = "character-voice",
  WORLD_BUILDER = "world-builder",
  PLOT_PREDICTOR = "plot-predictor",
  TENSION_OPTIMIZER = "tension-optimizer",
  CHARACTER_DEEP_ANALYZER = "character-deep-analyzer",
  DIALOGUE_ADVANCED_ANALYZER = "dialogue-advanced-analyzer",
  VISUAL_CINEMATIC_ANALYZER = "visual-cinematic-analyzer",
  THEMES_MESSAGES_ANALYZER = "themes-messages-analyzer",
  CULTURAL_HISTORICAL_ANALYZER = "cultural-historical-analyzer",
  PRODUCIBILITY_ANALYZER = "producibility-analyzer",
  TARGET_AUDIENCE_ANALYZER = "target-audience-analyzer",
  LITERARY_QUALITY_ANALYZER = "literary-quality-analyzer",
  RECOMMENDATIONS_GENERATOR = "recommendations-generator",
}

export enum TaskCategory {
  ANALYSIS = "ANALYSIS",
  CREATIVE = "CREATIVE",
  INTEGRATED = "INTEGRATED",
  GENERAL = "GENERAL",
  CHARACTER = "CHARACTER",
  SCENE = "SCENE",
  SCRIPT = "SCRIPT",
  CORE = "CORE",
  PREDICTIVE = "PREDICTIVE",
  ADVANCED_MODULES = "ADVANCED_MODULES",
}
